---
- name: Verifing if older Docker versions are installed
  gather_facts: false
  hosts: docker1
  become: yes
  tasks:  
    - name: Removing old docker packages
      package:
        name: '{{ item }}'
        state: absent
      loop:
        - docker 
        - docker-engine
        - docker.io
        - containerd
        - runc

- name: Install Dependencies and Repository
  gather_facts: false
  hosts: docker1
  become: yes
  tasks:  
    - name: Installing dependencies
      package:
        name: '{{ item }}'
        state: present
      loop:
        - apt-transport-https 
        - ca-certificates
        - curl 
        - gnupg-agent
        - software-properties-common

    - name: Add docker APT GPG Keys
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add specified docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu xenial stable
        state: present

- name: Install Docker
  gather_facts: false
  hosts: docker1
  become: yes
  tasks:  
    - name: Installing dependencies
      package:
        name: '{{ item }}'
        state: present
      loop:
        - docker-ce 
        - docker-ce-cli
        - containerd.io 
